<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    
<meta charset="UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>


<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />



  <meta name="description" content="Java异常处理"/>




  <meta name="keywords" content="Java," />




  <link rel="alternate" href="/atom.xml" title="Fynn's Blog" type="application/atom+xml">




  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?v=1.1.2" />



<link rel="canonical" href="https://fynn90.github.io/2020/11/14/Java异常处理/"/>


<meta name="description" content="异常是程序执行期间发生的意外事件。它影响程序指令的流程，这可能导致程序异常终止。 出于多种原因可能会发生异常。他们之中有一些是：  无效的用户输入 设备故障 网络连接丢失 物理限制（磁盘内存不足） 代码错误 打开一个不可用的文件  Java异常层次结构这是Java中异常层次结构的简化图:  Throwable类是层次结构中的根类。请注意，层次结构分为两个分支：Error和Exception。">
<meta property="og:type" content="article">
<meta property="og:title" content="Java异常处理">
<meta property="og:url" content="https://fynn90.github.io/2020/11/14/Java%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/index.html">
<meta property="og:site_name" content="Fynn&#39;s Blog">
<meta property="og:description" content="异常是程序执行期间发生的意外事件。它影响程序指令的流程，这可能导致程序异常终止。 出于多种原因可能会发生异常。他们之中有一些是：  无效的用户输入 设备故障 网络连接丢失 物理限制（磁盘内存不足） 代码错误 打开一个不可用的文件  Java异常层次结构这是Java中异常层次结构的简化图:  Throwable类是层次结构中的根类。请注意，层次结构分为两个分支：Error和Exception。">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://pic.downk.cc/item/5fa396021cd1bbb86b5214dc.png">
<meta property="og:image" content="https://pic.downk.cc/item/5fa934aa1cd1bbb86b84ac1c.png">
<meta property="article:published_time" content="2020-11-14T09:31:00.000Z">
<meta property="article:modified_time" content="2020-11-28T08:36:50.724Z">
<meta property="article:author" content="Fynn">
<meta property="article:tag" content="Java">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://pic.downk.cc/item/5fa396021cd1bbb86b5214dc.png">


<link rel="stylesheet" type="text/css" href="/css/style.css?v=1.1.2" />



  <link rel="stylesheet" type="text/css" href="/lib/fancybox/jquery.fancybox.css" />





<script>
  var CONFIG = {
    search: false,
    searchPath: "/search.xml",
    fancybox: true,
    toc: true,
  }
</script>




  
  <script type="text/javascript">
    var _hmt = _hmt || [];
    (function() {
      var hm = document.createElement("script");
      hm.src = "https://hm.baidu.com/hm.js?607980a031d3edcefed502ce80e77ffb";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
    })();
  </script>


  <script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-115728733-1', 'auto');
        ga('send', 'pageview');
  </script>



    <title> Java异常处理 · Fynn's Blog </title>
  <meta name="generator" content="Hexo 5.4.0"></head>

  <body><div id="mobile-navbar" class="mobile-navbar">
  <div class="mobile-header-logo">
    <a href="/." class="logo">Fynn's Blog</a>
  </div>
  <div class="mobile-navbar-icon">
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>

<nav id="mobile-menu" class="mobile-menu slideout-menu">
  <ul class="mobile-menu-list">
    
      <a href="/">
        <li class="mobile-menu-item">
          
          
            Home
          
        </li>
      </a>
    
      <a href="/archives/">
        <li class="mobile-menu-item">
          
          
            Archives
          
        </li>
      </a>
    
      <a href="/categories">
        <li class="mobile-menu-item">
          
          
            Categories
          
        </li>
      </a>
    
  </ul>
</nav>

    <div class="container" id="mobile-panel">
      <header id="header" class="header"><div class="logo-wrapper">
  <a href="/." class="logo">Fynn's Blog</a>
</div>

<nav class="site-navbar">
  
    <ul id="menu" class="menu">
      
        <li class="menu-item">
          <a class="menu-item-link" href="/">
            
            
              首页
            
          </a>
        </li>
      
        <li class="menu-item">
          <a class="menu-item-link" href="/archives/">
            
            
              归档
            
          </a>
        </li>
      
        <li class="menu-item">
          <a class="menu-item-link" href="/categories">
            
            
              分类
            
          </a>
        </li>
      
      
    </ul>
  
</nav>

      </header>

      <main id="main" class="main">
        <div class="content-wrapper">
          <div id="content" class="content">
            
  
  <article class="post">
    <header class="post-header">
      <h1 class="post-title">
        
          Java异常处理
        
      </h1>

      <div class="post-meta">
        <span class="post-time">
          2020年11月14日
        </span>
      </div>
    </header>

    
    
  <div class="post-toc" id="post-toc">
    <h2 class="post-toc-title">文章目录</h2>
    <div class="post-toc-content">
      <ol class="toc"><li class="toc-item toc-level-2"><a class="toc-link" href="#Java%E5%BC%82%E5%B8%B8%E5%B1%82%E6%AC%A1%E7%BB%93%E6%9E%84"><span class="toc-text">Java异常层次结构</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#Errors"><span class="toc-text">Errors</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#Exceptions"><span class="toc-text">Exceptions</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#Java%E5%BC%82%E5%B8%B8%E7%B1%BB%E5%9E%8B"><span class="toc-text">Java异常类型</span></a><ol class="toc-child"><li class="toc-item toc-level-4"><a class="toc-link" href="#RuntimeException"><span class="toc-text">RuntimeException</span></a></li><li class="toc-item toc-level-4"><a class="toc-link" href="#IOException"><span class="toc-text">IOException</span></a></li></ol></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#Java%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86"><span class="toc-text">Java异常处理</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E6%8D%95%E6%8D%89%E5%92%8C%E5%A4%84%E7%90%86%E5%BC%82%E5%B8%B8"><span class="toc-text">捕捉和处理异常</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#try%E2%80%A6catch-block"><span class="toc-text">try…catch block</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%A4%9A%E4%B8%AAcatch-%E6%A8%A1%E5%9D%97"><span class="toc-text">多个catch 模块</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#Java-finally"><span class="toc-text">Java finally</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#try-%E2%80%A6-catch%E8%AF%A6%E7%BB%86%E7%BB%86%E8%8A%82"><span class="toc-text">try … catch详细细节</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E6%8D%95%E8%8E%B7%E5%A4%9A%E4%B8%AA%E5%BC%82%E5%B8%B8"><span class="toc-text">捕获多个异常</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#try-width-resources-%E8%AF%AD%E5%8F%A5"><span class="toc-text">try-width-resources 语句</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#throw-%E5%92%8C-throws"><span class="toc-text">throw 和 throws</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#throws-%E5%85%B3%E9%94%AE%E5%AD%97"><span class="toc-text">throws 关键字</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%BC%95%E5%8F%91%E5%A4%9A%E4%B8%AA%E5%BC%82%E5%B8%B8"><span class="toc-text">引发多个异常</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#throws-VS-try%E2%80%A6catch%E2%80%A6finally"><span class="toc-text">throws VS try…catch…finally</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#throw-%E5%85%B3%E9%94%AE%E5%AD%97"><span class="toc-text">throw 关键字</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%8D%95%E8%8E%B7%E5%A4%9A%E4%B8%AA%E5%BC%82%E5%B8%B8-1"><span class="toc-text">捕获多个异常</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E4%B8%80%E4%B8%AAcatch-%E6%8D%95%E8%8E%B7%E5%A4%9A%E4%B8%AA%E5%BC%82%E5%B8%B8"><span class="toc-text">一个catch 捕获多个异常</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E6%8D%95%E8%8E%B7%E5%9F%BA%E7%A1%80%E5%BC%82%E5%B8%B8"><span class="toc-text">捕获基础异常</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#try-with-resources"><span class="toc-text">try-with-resources</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E8%A2%AB%E6%8A%91%E5%88%B6%E5%BC%82%E5%B8%B8"><span class="toc-text">被抑制异常</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E6%A3%80%E6%9F%A5%E8%A2%AB%E6%8A%91%E5%88%B6%E7%9A%84%E5%BC%82%E5%B8%B8"><span class="toc-text">检查被抑制的异常</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#try-with-resources%E7%9A%84%E4%BC%98%E5%8A%BF"><span class="toc-text">try-with-resources的优势</span></a><ol class="toc-child"><li class="toc-item toc-level-4"><a class="toc-link" href="#finally%E5%9D%97%E4%B8%8D%E9%9C%80%E8%A6%81%E5%85%B3%E9%97%AD%E8%B5%84%E6%BA%90"><span class="toc-text">finally块不需要关闭资源</span></a></li></ol></li><li class="toc-item toc-level-3"><a class="toc-link" href="#try-with-resources%E8%8E%B7%E5%8F%96%E5%A4%9A%E8%B5%84%E6%BA%90"><span class="toc-text">try-with-resources获取多资源</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#Java-9-%E5%A2%9E%E5%BC%BA-try-with-resources"><span class="toc-text">Java 9 增强 try-with-resources</span></a></li></ol></li></ol>
    </div>
  </div>


    <div class="post-content">
      
        <p>异常是程序执行期间发生的意外事件。它影响程序指令的流程，这可能导致程序异常终止。</p>
<p>出于多种原因可能会发生异常。他们之中有一些是：</p>
<ul>
<li>无效的用户输入</li>
<li>设备故障</li>
<li>网络连接丢失</li>
<li>物理限制（磁盘内存不足）</li>
<li>代码错误</li>
<li>打开一个不可用的文件</li>
</ul>
<h2 id="Java异常层次结构"><a href="#Java异常层次结构" class="headerlink" title="Java异常层次结构"></a><a target="_blank" rel="noopener" href="https://www.programiz.com/java-programming/exceptions">Java异常层次结构</a></h2><p>这是Java中异常层次结构的简化图:</p>
<p><img src="https://pic.downk.cc/item/5fa396021cd1bbb86b5214dc.png"></p>
<p><code>Throwable</code>类是层次结构中的根类。请注意，层次结构分为两个分支：<code>Error</code>和<code>Exception</code>。</p>
<span id="more"></span>

<h3 id="Errors"><a href="#Errors" class="headerlink" title="Errors"></a>Errors</h3><p>错误表示不可恢复的情况，例如Java虚拟机（JVM）内存不足，内存泄漏，堆栈溢出错误,库不兼容，无限递归等.</p>
<p>错误通常是程序员无法控制的，我们不应该尝试处理错误。</p>
<h3 id="Exceptions"><a href="#Exceptions" class="headerlink" title="Exceptions"></a>Exceptions</h3><p>程序可以捕获并处理异常。</p>
<p>当方法中发生异常时，它将创建一个对象。该对象称为异常对象。</p>
<p>它包含有关异常的信息，例如，异常的名称和说明以及发生异常时程序的状态。</p>
<h3 id="Java异常类型"><a href="#Java异常类型" class="headerlink" title="Java异常类型"></a>Java异常类型</h3><p>异常层次结构还具有两个分支：<code>RuntimeException</code>和<code>IOException</code>。</p>
<h4 id="RuntimeException"><a href="#RuntimeException" class="headerlink" title="RuntimeException"></a><code>RuntimeException</code></h4><p>由于编程错误而发生运行时异常,它们也称为非检查异常。</p>
<p>这些异常不在编译时检查，而是在运行时检查.一些常见的运行时异常是:</p>
<ul>
<li>API使用不当-<code>IllegalArgumentException</code></li>
<li>空指针访问（缺少变量的初始化）- <code>NullPointerException</code></li>
<li>越界数组访问 - <code>ArrayIndexOutOfBoundsException</code></li>
<li>将数字除以0 - <code>ArithmeticException</code></li>
</ul>
<p>你可以这么理解: “如果是运行时异常，那是您的错”。如果在使用变量之前检查了变量是否已初始化，则不会发生<code>NullPointerException</code>。</p>
<p>如果针对数组范围测试了数组索引，则不会发生<code>ArrayIndexOutOfBoundsException</code>。</p>
<h4 id="IOException"><a href="#IOException" class="headerlink" title="IOException"></a><code>IOException</code></h4><p><code>IOException</code>也称为检查异常。它们由编译器在编译时检查，并提示程序员处理这些异常。</p>
<p>受检查的异常的一些示例是：</p>
<ul>
<li>尝试打开不存在的文件会导致<code>FileNotFoundException</code></li>
<li>尝试读取文件末尾</li>
</ul>
<h2 id="Java异常处理"><a href="#Java异常处理" class="headerlink" title="Java异常处理"></a>Java异常处理</h2><p>异常是程序执行期间发生的意外事件</p>
<h3 id="捕捉和处理异常"><a href="#捕捉和处理异常" class="headerlink" title="捕捉和处理异常"></a>捕捉和处理异常</h3><p>在Java中，我们使用异常处理程序组件<code>try</code>, <code>catch</code>和<code>finally</code>块来处理异常</p>
<p>为了捕获和处理异常，我们在可能会生成异常的代码周围放置<code>try ... catch ... finally</code>块</p>
<p>,<code>finally</code>块是可选的.</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="comment">// code</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (ExceptionType e) &#123; </span><br><span class="line">  <span class="comment">// catch block</span></span><br><span class="line">&#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">  <span class="comment">// finally block</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h3 id="try…catch-block"><a href="#try…catch-block" class="headerlink" title="try…catch block"></a>try…catch block</h3><p>可能产生异常的代码放在<code>try</code>块中</p>
<p>每个<code>try</code>块应紧随<code>catch</code>或<code>finally</code>块,发生异常时,它会被紧随其后的<code>catch</code>块捕获。</p>
<p><code>catch</code>块不能单独使用，并且必须始终在<code>try</code>块之前。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">      <span class="keyword">int</span> divideByZero = <span class="number">5</span> / <span class="number">0</span>;</span><br><span class="line">      System.out.println(<span class="string">&quot;Rest of code in try block&quot;</span>);</span><br><span class="line">    &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;</span><br><span class="line">      System.out.println(<span class="string">&quot;ArithmeticException =&gt; &quot;</span> + e.getMessage());</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"><span class="comment">// 输出</span></span><br><span class="line"><span class="comment">// ArithmeticException =&gt; / by zero</span></span><br></pre></td></tr></table></figure>

<ul>
<li>我们在try块中将数字除以0。这将产生<code>ArithmeticException</code></li>
<li>发生异常时，程序将跳过<code>try</code>块中的其余代码</li>
<li>在这里，我们创建了一个<code>catch</code>块来处理<code>ArithmeticException</code>,因此，执行<code>catch</code>块内的语句。</li>
</ul>
<p>如果try块中的所有语句均未生成异常，则将跳过catch块.</p>
<h3 id="多个catch-模块"><a href="#多个catch-模块" class="headerlink" title="多个catch 模块"></a>多个catch 模块</h3><p>对于每个<code>try</code>块，可以有零个或多个<code>catch</code>块.</p>
<p>每个<code>catch</code>块的参数类型指示其可以处理的异常类型,多个<code>catch</code>块使我们能够以不同方式处理每个异常。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">ListOfNumbers</span> </span>&#123;</span><br><span class="line">  <span class="keyword">public</span> <span class="keyword">int</span>[] arrayOfNumbers = <span class="keyword">new</span> <span class="keyword">int</span>[<span class="number">10</span>];</span><br><span class="line"></span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">writeList</span><span class="params">()</span> </span>&#123;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">      arrayOfNumbers[<span class="number">10</span>] = <span class="number">11</span>;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (NumberFormatException e1) &#123;</span><br><span class="line">      System.out.println(<span class="string">&quot;NumberFormatException =&gt; &quot;</span> + e1.getMessage());</span><br><span class="line">    &#125; <span class="keyword">catch</span> (IndexOutOfBoundsException e2) &#123;</span><br><span class="line">      System.out.println(<span class="string">&quot;IndexOutOfBoundsException =&gt; &quot;</span> + e2.getMessage());</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    ListOfNumbers list = <span class="keyword">new</span> ListOfNumbers();</span><br><span class="line">    list.writeList();</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"><span class="comment">// 输出</span></span><br><span class="line"><span class="comment">// IndexOutOfBoundsException =&gt; Index 10 out of bounds for length 10</span></span><br></pre></td></tr></table></figure>

<p>在此示例中，声明了一个大小为10的整数<code>arrayOfNumbers</code>数组,我们知道数组索引总是从0开始。因此，当我们尝试为索引10分配一个值时，就会发生<code>IndexOutOfBoundsException</code>，因为<code>arrayOfNumbers</code>的数组范围是0到9。</p>
<p>当try块中发生异常时:</p>
<ul>
<li>异常被引发到第一个<code>catch</code>块。第一个<code>catch</code>块不处理<code>IndexOutOfBoundsException</code>，因此将其传递到下一个catch块。</li>
<li>上面示例中的第二个<code>catch</code>块是适当的异常处理程序，因为它处理<code>IndexOutOfBoundsException</code>。</li>
</ul>
<h3 id="Java-finally"><a href="#Java-finally" class="headerlink" title="Java finally"></a>Java finally</h3><p>对于每个<code>try</code>块，只能有一个<code>finally</code>块,<code>finally</code>块是可选的。但是，如果已定义，它将始终执行（即使不会发生异常）。</p>
<p>如果发生异常，则在<code>try ... catch</code>块之后执行该异常。如果没有异常发生，则在<code>try</code>块之后执行。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="comment">//code</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (ExceptionType1 e1) &#123; </span><br><span class="line">  <span class="comment">// catch block</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (ExceptionType1 e2) &#123;</span><br><span class="line"> <span class="comment">// catch block</span></span><br><span class="line">&#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">  <span class="comment">// finally block always executes</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">      <span class="keyword">int</span> divideByZero = <span class="number">5</span> / <span class="number">0</span>;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;</span><br><span class="line">      System.out.println(<span class="string">&quot;ArithmeticException =&gt; &quot;</span> + e.getMessage());</span><br><span class="line">    &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">      System.out.println(<span class="string">&quot;Finally block is always executed&quot;</span>);</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"><span class="comment">// 输出</span></span><br><span class="line"><span class="comment">// ArithmeticException =&gt; / by zero</span></span><br><span class="line"><span class="comment">// Finally block is always executed</span></span><br></pre></td></tr></table></figure>

<p>在此示例中，数字除以0。这引发了一个由<code>catch</code>块捕获的<code>ArithmeticException</code>,<code>finally</code>块始终执行。</p>
<p>进行最后<code>finally</code>被认为是一种好习惯。这是因为在此可以进行代码清理的动作，例如：</p>
<ul>
<li>返回，继续或中断语句可能意外跳过的代码</li>
<li>关闭文件或连接</li>
</ul>
<p>我们已经提到，<code>finally</code>总是执行，通常就是这种情况。但是，在某些情况下<code>finally</code>块不执行:</p>
<ul>
<li>使用<code>System.exit()</code>方法</li>
<li><code>finally</code>块中发生异常</li>
<li>线程挂掉</li>
</ul>
<p>举一个例子,我们尝试使用<code>FileWriter</code>创建一个新文件，然后使用<code>PrintWriter</code>将数据写入其中。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> java.io.*;</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">ListOfNumbers</span> </span>&#123;</span><br><span class="line">  <span class="keyword">private</span> <span class="keyword">int</span>[] list = <span class="keyword">new</span> <span class="keyword">int</span>[<span class="number">10</span>];</span><br><span class="line"></span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="title">ListOfNumbers</span><span class="params">()</span> </span>&#123;</span><br><span class="line">    <span class="comment">// storing integer values in the list array</span></span><br><span class="line">    <span class="keyword">for</span> (<span class="keyword">int</span> i = <span class="number">0</span>; i &lt; <span class="number">10</span>; i++) &#123;</span><br><span class="line">      list[i] = i;</span><br><span class="line">    &#125; 	</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">writeList</span><span class="params">()</span> </span>&#123;</span><br><span class="line">    PrintWriter out = <span class="keyword">null</span>;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">      System.out.println(<span class="string">&quot;Entering try statement&quot;</span>);</span><br><span class="line"></span><br><span class="line">      <span class="comment">// creating a new file OutputFile.txt</span></span><br><span class="line">      out = <span class="keyword">new</span> PrintWriter(<span class="keyword">new</span> FileWriter(<span class="string">&quot;OutputFile.txt&quot;</span>));</span><br><span class="line"></span><br><span class="line">      <span class="comment">// writing values from list array to the new created file</span></span><br><span class="line">      <span class="keyword">for</span> (<span class="keyword">int</span> i = <span class="number">0</span>; i &lt; <span class="number">10</span>; i++) &#123;</span><br><span class="line">        out.println(<span class="string">&quot;Value at: &quot;</span> + i + <span class="string">&quot; = &quot;</span> + list[i]);</span><br><span class="line">      &#125;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (IndexOutOfBoundsException e1) &#123;</span><br><span class="line">      System.out.println(<span class="string">&quot;IndexOutOfBoundsException =&gt; &quot;</span> + e1.getMessage());</span><br><span class="line">    &#125; <span class="keyword">catch</span> (IOException e2) &#123;</span><br><span class="line">      System.out.println(<span class="string">&quot;IOException =&gt; &quot;</span> + e2.getMessage());</span><br><span class="line">    &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">      <span class="comment">// checking if PrintWriter has been opened</span></span><br><span class="line">      <span class="keyword">if</span> (out != <span class="keyword">null</span>) &#123;</span><br><span class="line">        System.out.println(<span class="string">&quot;Closing PrintWriter&quot;</span>);</span><br><span class="line">        out.close();</span><br><span class="line">      &#125; <span class="keyword">else</span> &#123;</span><br><span class="line">        System.out.println(<span class="string">&quot;PrintWriter not open&quot;</span>);</span><br><span class="line">      &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    ListOfNumbers list = <span class="keyword">new</span> ListOfNumbers();</span><br><span class="line">    list.writeList();</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>当您运行此程序时，可能会发生两种可能性：</p>
<ul>
<li><code>try</code>块中发生异常</li>
<li><code>try</code>块正常执行</li>
</ul>
<p>创建新的<code>FileWriter</code>时可能会发生异常。如果无法创建或写入指定的文件，则抛出<code>IOException</code>。</p>
<p>当发生异常时，将获得以下输出:</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">Entering <span class="keyword">try</span> statement</span><br><span class="line">IOException =&gt; OutputFile.txt</span><br><span class="line">PrintWriter not open</span><br></pre></td></tr></table></figure>

<p>当未发生异常且<code>try</code>块正常执行时，将获得以下输出:</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">Entering <span class="keyword">try</span> statement</span><br><span class="line">Closing PrintWriter</span><br></pre></td></tr></table></figure>

<p>创建一个<code>OutputFile.txt</code>，它将具有以下内容：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line">Value at: <span class="number">0</span> = <span class="number">0</span></span><br><span class="line">Value at: <span class="number">1</span> = <span class="number">1</span></span><br><span class="line">Value at: <span class="number">2</span> = <span class="number">2</span></span><br><span class="line">Value at: <span class="number">3</span> = <span class="number">3</span></span><br><span class="line">Value at: <span class="number">4</span> = <span class="number">4</span></span><br><span class="line">Value at: <span class="number">5</span> = <span class="number">5</span></span><br><span class="line">Value at: <span class="number">6</span> = <span class="number">6</span></span><br><span class="line">Value at: <span class="number">7</span> = <span class="number">7</span></span><br><span class="line">Value at: <span class="number">8</span> = <span class="number">8</span></span><br><span class="line">Value at: <span class="number">9</span> = <span class="number">9</span></span><br></pre></td></tr></table></figure>

<h3 id="try-…-catch详细细节"><a href="#try-…-catch详细细节" class="headerlink" title="try … catch详细细节"></a>try … catch详细细节</h3><p>上述示例的帮助下详细了解异常处理的流程。</p>
<p><img src="https://pic.downk.cc/item/5fa934aa1cd1bbb86b84ac1c.png"></p>
<p>上图描述了在创建新<code>FileWriter</code>时发生异常时的程序执行流程。</p>
<ul>
<li>为了进入发生异常的方法，<code>main</code>方法中调用<code>writeList（）</code>方法，然后再调用<code>FileWriter（）</code>方法来创建新的<code>OutputFile.txt</code>文件。</li>
<li>发生异常时，运行时系统将跳过<code>try</code>块中的其余代码。</li>
<li>它开始以相反的顺序搜索调用堆栈，以找到合适的异常处理程序。</li>
<li>在这里，<code>FileWriter</code>没有异常处理程序，因此运行时系统检查调用堆栈中的下一个方法，即<code>writeList</code>。</li>
<li><code>writeList</code>方法有两个异常处理程序：一个处理<code>IndexOutOfBoundsException</code>，另一个处理<code>IOException</code>。</li>
<li>然后，系统按顺序处理这些处理程序。</li>
<li>此示例中的第一个处理程序处理<code>IndexOutOfBoundsException</code>这与<code>try</code>块引发的<code>IOException</code>不匹配。</li>
<li>因此，将检查下一个处理程序，即<code>IOException</code>处理程序这与抛出的异常类型匹配，因此执行<code>catch</code>块中的代码。</li>
<li>执行异常处理程序后，将执行<code>finally</code>块。</li>
<li>在这种情况下，由于<code>FileWriter</code>中发生异常，因此<code>PrintWriter</code>对象<code>out</code>永远不会打开，因此不需要关闭。</li>
</ul>
<p>现在，让我们假设在运行该程序时没有发生异常，并且<code>try</code>块正常执行。在这种情况下，将创建并写入<code>一个OutputFile.txt</code>。</p>
<p>众所周知，无论异常处理如何，都将执行<code>finally</code>块。由于没有发生异常，因此<code>PrintWriter</code>是打开的，则需要关闭。这是通过<code>finally</code>块中的<code>out.close（）</code>语句完成的。</p>
<h3 id="捕获多个异常"><a href="#捕获多个异常" class="headerlink" title="捕获多个异常"></a>捕获多个异常</h3><p>从Java SE 7和更高版本开始，我们现在可以通过一个catch块捕获不止一种类型的异常。</p>
<p>这样可以减少代码重复并提高代码的简单性和效率。</p>
<p><code>catch</code>块可以处理的每种异常类型都使用竖线|分隔。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="comment">// code</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (ExceptionType1 | Exceptiontype2 ex) &#123; </span><br><span class="line">  <span class="comment">// catch block</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h3 id="try-width-resources-语句"><a href="#try-width-resources-语句" class="headerlink" title="try-width-resources 语句"></a>try-width-resources 语句</h3><p><code>try-with-resources</code>语句是一种try语句，具有一个或多个资源声明。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> (resource declaration) &#123;</span><br><span class="line">  <span class="comment">// use of the resource</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (ExceptionType e1) &#123;</span><br><span class="line">  <span class="comment">// catch block</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>资源是在程序结束时要关闭的对象。必须在try语句中声明和初始化它。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> (PrintWriter out = <span class="keyword">new</span> PrintWriter(<span class="keyword">new</span> FileWriter(“OutputFile.txt”)) &#123;</span><br><span class="line">  <span class="comment">// use of the resource</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><code>try-with-resources</code> 语句也称为自动资源管理。该语句在语句末尾自动关闭所有资源。</p>
<h2 id="throw-和-throws"><a href="#throw-和-throws" class="headerlink" title="throw 和 throws"></a>throw 和 throws</h2><p>在Java中，异常可以分为两种类型:</p>
<ul>
<li><p><strong>Unchecked Exceptions:</strong> 它们不是在编译时检查的，而是在运行时检查的。例子:</p>
<p><code>ArithmeticException</code>, <code>NullPointerException</code>, <code>ArrayIndexOutOfBoundsException</code>,<code>Error</code>类下的异常等</p>
</li>
<li><p><strong>Checked Exceptions:</strong> 它们在编译时检查.例子: <code>IOException</code>, <code>InterruptedException</code>.</p>
</li>
</ul>
<p>通常，我们不需要处理<code>Unchecked Exceptions</code>的异常。因为<code>Unchecked Exceptions</code>是代码逻辑有问题.最好的习惯是,解决它而不是捕获它.</p>
<h3 id="throws-关键字"><a href="#throws-关键字" class="headerlink" title="throws 关键字"></a>throws 关键字</h3><p>我们在方法声明中使用<code>throws</code>关键字来声明其中可能发生的异常的类型。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="function">accessModifier returnType <span class="title">methodName</span><span class="params">()</span> <span class="keyword">throws</span> ExceptionType1, ExceptionType2 … </span>&#123;</span><br><span class="line">  <span class="comment">// code</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>从上面的语法可以看到:使用<code>throws</code>声明多个异常。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> java.io.*;</span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">findFile</span><span class="params">()</span> <span class="keyword">throws</span> IOException </span>&#123;</span><br><span class="line">    <span class="comment">// code that may produce IOException</span></span><br><span class="line">    File newFile=<span class="keyword">new</span> File(<span class="string">&quot;test.txt&quot;</span>);</span><br><span class="line">    FileInputStream stream=<span class="keyword">new</span> FileInputStream(newFile);</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    <span class="keyword">try</span>&#123;</span><br><span class="line">      findFile();</span><br><span class="line">    &#125; <span class="keyword">catch</span>(IOException e)&#123;</span><br><span class="line">      System.out.println(e);</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// 输出</span></span><br><span class="line"><span class="comment">// java.io.FileNotFoundException: test.txt (No such file or directory)</span></span><br></pre></td></tr></table></figure>

<p>当我们运行该程序时，如果文件<code>test.txt</code>不存在，则<code>FileInputStream</code>抛出一个<code>FileNotFoundException</code>，它扩展了<code>IOException</code>类。</p>
<p>如果方法不处理异常,必须在<code>throws</code>子句中指定其中可能发生的异常的类型，以便调用堆栈中更远的方法可以处理它们。</p>
<p><code>findFile()</code>方法指定可以抛出<code>IOException</code>。<code>main()</code>方法调用此方法并处理抛出的异常。</p>
<h3 id="引发多个异常"><a href="#引发多个异常" class="headerlink" title="引发多个异常"></a>引发多个异常</h3><p>这是我们可以使用<code>throws</code>关键字引发多个异常的方法。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> java.io.*;</span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">findFile</span><span class="params">()</span> <span class="keyword">throws</span> NullPointerException, IOException, InvalidClassException </span>&#123;</span><br><span class="line">    </span><br><span class="line">    <span class="comment">// code that may produce NullPointerException</span></span><br><span class="line">    … … … </span><br><span class="line"></span><br><span class="line">    <span class="comment">// code that may produce IOException</span></span><br><span class="line">    … … … </span><br><span class="line"></span><br><span class="line">    <span class="comment">// code that may produce InvalidClassException </span></span><br><span class="line">    … … … </span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    <span class="keyword">try</span>&#123;</span><br><span class="line">      findFile();</span><br><span class="line">    &#125; <span class="keyword">catch</span>(IOException e1)&#123;</span><br><span class="line">      System.out.println(e1.getMessage());</span><br><span class="line">    &#125; <span class="keyword">catch</span>(InvalidClassException e2)&#123;</span><br><span class="line">      System.out.println(e2.getMessage());</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><code>findFile()</code>方法指定它可以在其<code>throws</code>子句中引发<code>NullPointerException</code>，<code>IOException</code>和<code>InvalidClassException</code>。</p>
<p>请注意我们尚未处理<code>NullPointerException</code>.因为它是<code>unchecked exception</code>.不必在<code>throws</code>子句中指定它并进行处理。</p>
<h3 id="throws-VS-try…catch…finally"><a href="#throws-VS-try…catch…finally" class="headerlink" title="throws VS try…catch…finally"></a>throws VS try…catch…finally</h3><p>可能有几种方法可能导致异常。为每种方法编写<code>try ... catch</code>会很乏味，并且代码会变得很长且可读性较差。</p>
<p>当你在当前方法并不想处理异常, 但你检测了有可能的异常,那么<code>throws</code>是个很有用.</p>
<h3 id="throw-关键字"><a href="#throw-关键字" class="headerlink" title="throw 关键字"></a>throw 关键字</h3><p><code>throw</code>关键字用于显式引发单个异常</p>
<p>引发异常时，程序执行流程从<code>try</code>块转移到<code>catch</code>块</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">throw</span> throwableObject;</span><br></pre></td></tr></table></figure>

<p><code>Throwable</code>对象是<code>Throwable</code>类或<code>Throwable</code>类的子类的实例。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">divideByZero</span><span class="params">()</span> </span>&#123;</span><br><span class="line">    <span class="keyword">throw</span> <span class="keyword">new</span> ArithmeticException(<span class="string">&quot;Trying to divide by 0&quot;</span>);</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    divideByZero();</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>输出:</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">Exception in thread <span class="string">&quot;main&quot;</span> java.lang.ArithmeticException: Trying to divide by <span class="number">0</span></span><br><span class="line">    at Main.divideByZero(Main.java:<span class="number">3</span>)</span><br><span class="line">    at Main.main(Main.java:<span class="number">7</span>)</span><br><span class="line">exit status <span class="number">1</span></span><br></pre></td></tr></table></figure>

<p>在此示例中，我们显式抛出<code>ArithmeticException</code>。</p>
<p><strong>注意:</strong> <code>ArithmeticException</code>是<code>unchecked exception</code>,通常没有必要处理。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> java.io.*;</span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">findFile</span><span class="params">()</span> <span class="keyword">throws</span> IOException </span>&#123;</span><br><span class="line">    <span class="keyword">throw</span> <span class="keyword">new</span> IOException(<span class="string">&quot;File not found&quot;</span>);</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">      findFile();</span><br><span class="line">      System.out.println(<span class="string">&quot;Rest of code in try block&quot;</span>);</span><br><span class="line">    &#125; <span class="keyword">catch</span> (IOException e) &#123;</span><br><span class="line">      System.out.println(e.getMessage());</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>输出:</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">File not found</span><br></pre></td></tr></table></figure>

<p><code>findFile()</code>方法会引发<code>IOException</code>以及我们传递给其构造函数的消息</p>
<p>请注意由于它是一个<code>checked exception</code>，因此必须在<code>throws</code>子句中指定它</p>
<p>调用此<code>findFile()</code>方法的方法需要处理此异常，或者自己使用throws关键字指定它</p>
<p>我们已经在<code>main()</code>方法中处理了这个异常。引发异常时程序执行流程从<code>try</code>块转移到<code>catch</code>块。因此将跳过<code>try</code>块中的其余代码，并执行<code>catch</code>块中的语句</p>
<h2 id="捕获多个异常-1"><a href="#捕获多个异常-1" class="headerlink" title="捕获多个异常"></a>捕获多个异常</h2><p>在Java 7之前即使存在代码冗余，我们也必须针对不同类型的异常编写多个异常处理代码。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">      <span class="keyword">int</span> array[] = <span class="keyword">new</span> <span class="keyword">int</span>[<span class="number">10</span>];</span><br><span class="line">      array[<span class="number">10</span>] = <span class="number">30</span> / <span class="number">0</span>;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;</span><br><span class="line">      System.out.println(e.getMessage());</span><br><span class="line">    &#125; <span class="keyword">catch</span> (ArrayIndexOutOfBoundsException e) &#123;</span><br><span class="line">      System.out.println(e.getMessage());</span><br><span class="line">    &#125; </span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"><span class="comment">// 输出</span></span><br><span class="line"><span class="comment">// / by zero</span></span><br></pre></td></tr></table></figure>

<p>在此的示例可能会发生两个异常：</p>
<ul>
<li><code>ArithmeticException</code>因为我们试图将数字除以0.</li>
<li><code>ArrayIndexOutOfBoundsException</code>因为我们已经声明了一个新的整数数组，其数组边界为0到9，并且我们试图为索引10分配一个值</li>
</ul>
<p>我们正在两个catch块中打印出异常消息，即重复代码</p>
<h3 id="一个catch-捕获多个异常"><a href="#一个catch-捕获多个异常" class="headerlink" title="一个catch 捕获多个异常"></a>一个catch 捕获多个异常</h3><p>在Java SE 7和更高版本中，我们现在可以在单个catch块中捕获不止一种类型的异常</p>
<p><code>catch</code>块可以处理的每种异常类型都使用竖线或竖线<code>|</code>分隔</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="comment">// code</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (ExceptionType1 | Exceptiontype2 ex) &#123; </span><br><span class="line">  <span class="comment">// catch block</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">      <span class="keyword">int</span> array[] = <span class="keyword">new</span> <span class="keyword">int</span>[<span class="number">10</span>];</span><br><span class="line">      array[<span class="number">10</span>] = <span class="number">30</span> / <span class="number">0</span>;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (ArithmeticException | ArrayIndexOutOfBoundsException e) &#123;</span><br><span class="line">      System.out.println(e.getMessage());</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"><span class="comment">// 输出</span></span><br><span class="line"><span class="comment">// / by zero</span></span><br></pre></td></tr></table></figure>

<p>在单<code>·catch</code>块中捕获多个异常可以减少代码重复并提高效率。</p>
<p>编译该程序时生成的字节码将比具有多个捕获块的程序小，因为没有代码冗余。</p>
<p><strong>注意:</strong> 如果<code>catch</code>块处理多个异常，则<code>catch</code>参数隐式为<code>final</code>。这意味着我们无法分配任何值来捕获参数</p>
<h3 id="捕获基础异常"><a href="#捕获基础异常" class="headerlink" title="捕获基础异常"></a>捕获基础异常</h3><p>当在单个<code>catch</code>块中捕获多个异常时，该规则一般化为专门化。</p>
<p>这意味着，如果<code>catch</code>块中存在异常的层次结构，我们只能捕获基本异常，而不是捕获多个专门的异常。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">      <span class="keyword">int</span> array[] = <span class="keyword">new</span> <span class="keyword">int</span>[<span class="number">10</span>];</span><br><span class="line">      array[<span class="number">10</span>] = <span class="number">30</span> / <span class="number">0</span>;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">      System.out.println(e.getMessage());</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"><span class="comment">// 输出</span></span><br><span class="line"><span class="comment">// / by zero</span></span><br></pre></td></tr></table></figure>

<p>我们知道所有异常类都是<code>Exception</code>类的子类。因此我们不必捕获多个专门的异常，而只需捕获<code>Exception</code>类。</p>
<p>如果在<code>catch</code>块中已经指定了基本异常类，则不要在同一<code>catch</code>块中使用子异常类。否则我们会得到一个编译错误。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">      <span class="keyword">int</span> array[] = <span class="keyword">new</span> <span class="keyword">int</span>[<span class="number">10</span>];</span><br><span class="line">      array[<span class="number">10</span>] = <span class="number">30</span> / <span class="number">0</span>;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (Exception | ArithmeticException | ArrayIndexOutOfBoundsException e) &#123;</span><br><span class="line">      System.out.println(e.getMessage());</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>输出:</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">Main.java:<span class="number">6</span>: error: Alternatives in a multi-<span class="keyword">catch</span> statement cannot be related by subclassing</span><br></pre></td></tr></table></figure>

<p>在此示例中，<code>ArithmeticException</code>和`ArrayIndexOutOfBoundsException都是Exception类的子类,所以编译错误.</p>
<h2 id="try-with-resources"><a href="#try-with-resources" class="headerlink" title="try-with-resources"></a>try-with-resources</h2><p><code>try-with-resources</code>语句末尾自动关闭所有资源.资源是程序结束时要关闭的对象。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> (resource declaration) &#123;</span><br><span class="line">  <span class="comment">// use of the resource</span></span><br><span class="line">&#125; <span class="keyword">catch</span> (ExceptionType e1) &#123;</span><br><span class="line">  <span class="comment">// catch block</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>从上面的语法可以看出，我们通过以下方式声明<code>try-with-resources</code>语句：</p>
<ul>
<li>在<code>try</code>子句中声明和实例化资源。</li>
<li>指定并处理关闭资源时可能引发的所有异常。</li>
</ul>
<p><strong>注意：</strong> <code>try-with-resources</code>语句关闭实现<code>AutoCloseable</code>接口的所有资源。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> java.io.*;</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    String line;</span><br><span class="line">    <span class="keyword">try</span>(BufferedReader br = <span class="keyword">new</span> BufferedReader(<span class="keyword">new</span> FileReader(<span class="string">&quot;test.txt&quot;</span>))) &#123;</span><br><span class="line">      <span class="keyword">while</span> ((line = br.readLine()) != <span class="keyword">null</span>) &#123;</span><br><span class="line">        System.out.println(<span class="string">&quot;Line =&gt;&quot;</span>+line);</span><br><span class="line">      &#125;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (IOException e) &#123;</span><br><span class="line">      System.out.println(<span class="string">&quot;IOException in try block =&gt;&quot;</span> + e.getMessage());</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>如果<code>test.txt</code>文件没找到:</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">IOException in <span class="keyword">try</span>-with-resources block =&gt;test.txt (No such file or directory)</span><br></pre></td></tr></table></figure>

<p>如果<code>test.text</code>文件找到</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">Entering <span class="keyword">try</span>-with-resources block</span><br><span class="line">Line =&gt;test line</span><br></pre></td></tr></table></figure>

<p>在此示例中，使用<code>BufferedReader</code>的实例从<code>test.txt</code>文件读取数据</p>
<p>在<code>try-with-resources</code>语句中声明并实例化<code>BufferedReader</code>可以确保关闭其实例，而不管<code>try</code>语句是正常完成还是引发异常。</p>
<p>如果发生异常，则可以使用异常处理块或<code>throws</code>关键字对其进行处理。</p>
<h3 id="被抑制异常"><a href="#被抑制异常" class="headerlink" title="被抑制异常"></a>被抑制异常</h3><p>在上面的示例中，在以下情况下，可以从<code>try-with-resources</code>语句引发异常：</p>
<ul>
<li>找不到文件<code>test.txt</code></li>
<li>关闭<code>BufferedReader</code>对象</li>
</ul>
<p>也可以从<code>try</code>块中引发异常，因为文件读取可能随时因多种原因而失败。</p>
<p>如果<code>try</code>块和<code>try-with-resources</code>语句都抛出了异常,将抛出<code>try</code>块中的异常，并抑制<code>try-with-resources</code>语句中的异常。</p>
<h3 id="检查被抑制的异常"><a href="#检查被抑制的异常" class="headerlink" title="检查被抑制的异常"></a>检查被抑制的异常</h3><p>在Java 7和更高版本中，可以通过从<code>try</code>块引发的异常中调用<code>Throwable.getSuppressed()</code>方法来检索受抑制的异常。</p>
<p>此方法返回所有抑制的异常的数组。我们在<code>catch</code>块中得到了抑制的异常。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">catch</span>(IOException e) &#123;</span><br><span class="line">  System.out.println(<span class="string">&quot;Thrown exception=&gt;&quot;</span> + e.getMessage());</span><br><span class="line">  Throwable[] suppressedExceptions = e.getSuppressed();</span><br><span class="line">  <span class="keyword">for</span> (<span class="keyword">int</span> i=<span class="number">0</span>; i&lt;suppressedExceptions.length; i++) &#123;</span><br><span class="line">    System.out.println(<span class="string">&quot;Suppressed exception=&gt;&quot;</span> + suppressedExceptions[i]);</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h3 id="try-with-resources的优势"><a href="#try-with-resources的优势" class="headerlink" title="try-with-resources的优势"></a><code>try-with-resources</code>的优势</h3><h4 id="finally块不需要关闭资源"><a href="#finally块不需要关闭资源" class="headerlink" title="finally块不需要关闭资源"></a><code>finally</code>块不需要关闭资源</h4><p>在Java 7引入此功能之前，我们必须使用<code>finally</code>块来确保关闭资源以避免资源泄漏。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> java.io.*;</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">    BufferedReader br = <span class="keyword">null</span>;</span><br><span class="line">    String line;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">      System.out.println(<span class="string">&quot;Entering try block&quot;</span>);</span><br><span class="line">      br = <span class="keyword">new</span> BufferedReader(<span class="keyword">new</span> FileReader(<span class="string">&quot;test.txt&quot;</span>));</span><br><span class="line">      <span class="keyword">while</span> ((line = br.readLine()) != <span class="keyword">null</span>) &#123;</span><br><span class="line">        System.out.println(<span class="string">&quot;Line =&gt;&quot;</span>+line);</span><br><span class="line">      &#125;</span><br><span class="line">    &#125; <span class="keyword">catch</span> (IOException e) &#123;</span><br><span class="line">      System.out.println(<span class="string">&quot;IOException in try block =&gt;&quot;</span> + e.getMessage());</span><br><span class="line">    &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">      System.out.println(<span class="string">&quot;Entering finally block&quot;</span>);</span><br><span class="line">      <span class="keyword">try</span> &#123;</span><br><span class="line">        <span class="keyword">if</span> (br != <span class="keyword">null</span>) &#123;</span><br><span class="line">          br.close();</span><br><span class="line">        &#125;</span><br><span class="line">      &#125; <span class="keyword">catch</span> (IOException e) &#123;</span><br><span class="line">        System.out.println(<span class="string">&quot;IOException in finally block =&gt;&quot;</span>+e.getMessage());</span><br><span class="line">      &#125;</span><br><span class="line"></span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>输出:</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">Entering <span class="keyword">try</span> block</span><br><span class="line">Line =&gt;line from test.txt file</span><br><span class="line">Entering <span class="keyword">finally</span> block </span><br></pre></td></tr></table></figure>

<p>从上面的示例可以看出，使用<code>finally</code>块来清理资源使代码更加复杂。</p>
<p>还要注意<code>finally</code>块中的<code>try ... catch</code>块吗？这是因为在关闭此<code>finally</code>块内的<code>BufferedReader</code>实例时也可能发生<code>IOException</code>，因此也将其捕获并处理。</p>
<p><code>try-with-resources</code>语句执行自动资源管理,我们不需要显式关闭资源，因为JVM会自动关闭它们。这使代码更具可读性，更易于编写。</p>
<h3 id="try-with-resources获取多资源"><a href="#try-with-resources获取多资源" class="headerlink" title="try-with-resources获取多资源"></a><code>try-with-resources</code>获取多资源</h3><p>我们可以在<code>try-with-resources</code>语句中声明多个资源，方法是用<code>;</code>将它们分开.</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> java.io.*;</span><br><span class="line"><span class="keyword">import</span> java.util.*;</span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Main</span> </span>&#123;</span><br><span class="line">  <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> <span class="keyword">throws</span> IOException</span>&#123;</span><br><span class="line">    <span class="keyword">try</span> (Scanner scanner = <span class="keyword">new</span> Scanner(<span class="keyword">new</span> File(<span class="string">&quot;testRead.txt&quot;</span>)); </span><br><span class="line">      PrintWriter writer = <span class="keyword">new</span> PrintWriter(<span class="keyword">new</span> File(<span class="string">&quot;testWrite.txt&quot;</span>))) &#123;</span><br><span class="line">      <span class="keyword">while</span> (scanner.hasNext()) &#123;</span><br><span class="line">        writer.print(scanner.nextLine());</span><br><span class="line">      &#125;</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>如果该程序执行时未生成任何异常,<code>Scanner</code>对象从testRead.txt文件中读取一行并将其写入新的testWrite.txt文件中。</p>
<p>进行多个声明时,<code>try-with-resources</code>语句以相反的顺序关闭这些资源。在此示例中，首先关闭<code>PrintWriter</code>对象，然后关闭<code>Scanner</code>对象。</p>
<h3 id="Java-9-增强-try-with-resources"><a href="#Java-9-增强-try-with-resources" class="headerlink" title="Java 9 增强 try-with-resources"></a>Java 9 增强 <code>try-with-resources</code></h3><p>在Java 7中，<code>try-with-resources</code>语句受到限制,该资源需要在其块内本地声明。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> (Scanner scanner = <span class="keyword">new</span> Scanner(<span class="keyword">new</span> File(<span class="string">&quot;testRead.txt&quot;</span>))) &#123;</span><br><span class="line">  <span class="comment">// code</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>如果我们在Java 7中在块外声明资源,它会生成一条错误消息。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">Scanner scanner = <span class="keyword">new</span> Scanner(<span class="keyword">new</span> File(<span class="string">&quot;testRead.txt&quot;</span>));</span><br><span class="line"><span class="keyword">try</span> (scanner) &#123;</span><br><span class="line">  <span class="comment">// code</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>处理此错误,Java 9改进了<code>try-with-resources</code>语句，因此即使未在本地声明资源的引用，也可以使用。上面的代码现在将执行，没有任何编译错误。</p>

      
    </div>

    
      
      

  <div class="post-copyright">
    <p class="copyright-item">
      <span>作者: </span>
      <span>Fynn</span>
    </p>
    <p class="copyright-item">
      <span>来源: </span>
      <a href="https://fynn90.github.io">https://fynn90.github.io</a>
    </p>
    <p class="copyright-item">
      <span>链接: </span>
      <a href="https://fynn90.github.io/2020/11/14/Java%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/">https://fynn90.github.io/2020/11/14/Java%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/</a>
    </p>

    <p class="copyright-item lincese">
      
      本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可
    </p>
  </div>



      
      
  <div class="post-reward">
    <input type="checkbox" name="reward" id="reward" hidden />
    <label class="reward-button" for="reward">赞赏支持</label>
    <div class="qr-code">
      
      
        <label class="qr-code-image" for="reward">
          <img class="image" src="/image/reward/wechat.png" title="wechat">
          <div>wechat</div>
        </label>
      
      
        <label class="qr-code-image" for="reward">
          <img class="image" src="/image/reward/alipay.png" title="alipay">
          <div>alipay</div>
        </label>
      
    </div>
  </div>

    

    
      <footer class="post-footer">
        
          <div class="post-tags">
            
              <a href="/tags/Java/">Java</a>
            
          </div>
        
        
        
  <nav class="post-nav">
    
      <a class="prev" href="/2020/12/20/%E5%BE%AE%E5%89%8D%E7%AB%AF%E7%9A%84%E5%89%8D%E4%B8%96%E4%BB%8A%E7%94%9F/">
        <i class="iconfont icon-left"></i>
        <span class="prev-text nav-default">微前端的前世今生</span>
        <span class="prev-text nav-mobile">上一篇</span>
      </a>
    
    
      <a class="next" href="/2020/10/30/Java%E7%9A%84OOP/">
        <span class="next-text nav-default">Java的OOP</span>
        <span class="prev-text nav-mobile">下一篇</span>
        <i class="iconfont icon-right"></i>
      </a>
    
  </nav>

      </footer>
    

  </article>


          </div>
          
  <div class="comments" id="comments">
    
  </div>


        </div>  
      </main>

      <footer id="footer" class="footer">

  <div class="social-links">
    
      
        
          <a href="mailto:fynn.90@outlook.com" class="iconfont icon-email" title="email"></a>
        
      
    
      
    
      
    
      
    
      
        
          <a target="_blank" rel="noopener" href="https://www.linkedin.com/in/%E5%B8%86-%E9%82%93-17163589/" class="iconfont icon-linkedin" title="linkedin"></a>
        
      
    
      
        
          <a target="_blank" rel="noopener" href="https://plus.google.com/u/0/117459332873536225443" class="iconfont icon-google" title="google"></a>
        
      
    
      
        
          <a target="_blank" rel="noopener" href="https://github.com/fatefan" class="iconfont icon-github" title="github"></a>
        
      
    
      
        
          <a target="_blank" rel="noopener" href="http://www.weibo.com/306019091" class="iconfont icon-weibo" title="weibo"></a>
        
      
    
      
        
          <a target="_blank" rel="noopener" href="https://www.zhihu.com/people/FynnDeng/activities" class="iconfont icon-zhihu" title="zhihu"></a>
        
      
    
      
    
    
    
  </div>


<div class="copyright">
  
  <span class="copyright-year">
    
    &copy; 
     
      2017 - 
    
    2022

    <span class="heart">
      <i class="iconfont icon-heart"></i>
    </span>
    <span class="author">Fynn</span>
  </span>
  
</div>
      </footer>

      <div class="back-to-top" id="back-to-top">
        <i class="iconfont icon-up"></i>
      </div>
    </div>

    
  

  
  




    
  





  
    <script type="text/javascript" src="/lib/jquery/jquery-3.1.1.min.js"></script>
  

  
    <script type="text/javascript" src="/lib/slideout/slideout.js"></script>
  

  
    <script type="text/javascript" src="/lib/fancybox/jquery.fancybox.pack.js"></script>
  


    <script type="text/javascript" src="/js/src/even.js?v=1.1.2"></script>
<script type="text/javascript" src="/js/src/bootstrap.js?v=1.1.2"></script>

    
  </body>
</html>
